# Generated by Django 6.0.3 on 2026-04-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezfitAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietplans',
            old_name='user_id',
            new_name='user',
        ),
    ]
