# Generated by Django 6.0.3 on 2026-03-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezfitAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplans',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
